# Generated by Django 2.2 on 2021-02-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
