# Generated by Django 2.2 on 2021-02-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task1', '0002_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
